### ISSUE TITLE
裁剪otf字体时出错

### ISSUE THREAD

**Issue by ZeroUltra** [821869798/fontsubset#1]
![image](https://github.com/user-attachments/assets/6c4d28ed-9a51-41b0-a4bc-5b75772fda1f)
裁剪得是思源宋体出现这个情况

**Comment by 821869798** [comment]
这个字体没有loca和glyf表，这两个表是TrueType类型字体必须的。你这个应该是PostScript类型的字体所以是不支持的。

**Comment by ZeroUltra** [comment]
好的,对字体不是很了解,请问下怎么知道这个字体是否有loca和glyf表呢

**Comment by 821869798** [comment]
双击打开字体，如下图所示，PostScript字体不支持，下面的TrueType才支持。
如果真要用这个字体，可以使用FontFontCreator把PostScript字体转为TrueType的，我自己试了可以使用。
![image](https://github.com/user-attachments/assets/1c102f4b-e57c-42b3-a4ef-9a06a614fd52)
![image](https://github.com/user-attachments/assets/94686a9f-a98e-499d-9382-3957dc8c700a)

[FontCreator下载](https://forum.freemdict.com/t/topic/28083)

**Comment by ZeroUltra** [comment]
非常感谢哦~❤
