### ISSUE TITLE
是否可以添加结果信息

### ISSUE THREAD

**Issue by ZeroUltra** [821869798/fontsubset#2]
使用下来没啥问题,  现在就是想在裁剪完成之后能否输出(或者直接对话框显示)一些信息,当然这可以使用别的字体软件查看,如果要是方便的话能否加上.
例如:显示裁剪之后的字体有多少字, 想要这个的原因就是怕字体中原先就没有某些字,导致最后裁剪的字也没有该字

**Comment by 821869798** [comment]
这个需要有空的时间开发一下，是弹框中显示的裁剪前多少字裁剪后多少字吗。

**Comment by ZeroUltra** [comment]
嗯嗯 对的,感谢
另外问下如果加一个反向裁剪功能是否方便，即给定一个文字集和源字体，源字体会剔除文字集的所有文字(如果源文字含有的该字)，然后保留剩下的字输出新字体
