### ISSUE TITLE
希望得使用授权(非商用)

### ISSUE THREAD

**Issue by jason21415** [821869798/fontsubset#4]
你好
我正在开发一款游戏工具,希望能使用该储存库的这个工具.
请问能给我使用的授权吗?
如果可以请添加一个授权说明页面在该储存库README.md中.
https://github.com/821869798/fontsubset

授权种类介绍
https://www.gnu.org/licenses/licenses.zh-cn.html
https://www.gnu.org/licenses/license-recommendations.html
正在开发的游戏工具
https://github.com/StefanOltmann/oni-seed-browser?tab=AGPL-3.0-1-ov-file

**Comment by 821869798** [comment]
已添加[MIT license](https://github.com/821869798/fontsubset#MIT-1-ov-file)

**Comment by jason21415** [comment]
谢谢
